#!/bin/bash

OPENJFX=/usr/share/openjfx/lib
# OPENJFX=/home/$USER/jfx/build/sdk/lib

###
# Check for support packages: lookFor.
#
if [ -z "$(type lf 2>/dev/null)" ]; then
    echo "Error! The lookFor package is not installed, but is required."
    echo "   see: https://github.com/markcapella/lookFor"
    echo 
    exit 1
fi

###
# If lookForSelect can't find a desktop for it's GUI selection window,
# then output is produced to stdout.
#
if [ -z "$XDG_CURRENT_DESKTOP" ]; then
    lf "$1" "$2" "$3"
    exit 0
fi

###
# Execute the lookForSelect GUI.
#
RESULT=$(lf "$1" "$2" "$3" | java \
    --module-path "$OPENJFX" \
    --add-modules javafx.controls,javafx.swing,javafx.media \
    --class-path /usr/local/lookForSelect \
    lookForSelect) 2>/dev/null

###
# Let xdg-open perform file action based on mime type.
#
if [ -n "$RESULT" ]; then
    xdg-open $RESULT 1>/dev/null 2>/dev/null
fi
